[project]
name = "torch-to-triton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.9.0",
    "modal>=1.1.0",
    "torch>=2.7.1",
    "transformers>=4.54.0",
]
